# Generated by Django 5.0.2 on 2024-04-25 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='totalActivity',
            new_name='total',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='valueActivity',
            new_name='value',
        ),
    ]
