# Generated by Django 5.0.7 on 2024-07-18 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitycontrol', '0002_rename_totalactivity_activity_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('dateStart', models.FloatField()),
                ('dateEnd', models.FloatField()),
                ('activity', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('total', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
