# Generated by Django 5.0.7 on 2024-07-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitycontrol', '0003_activitycontrol_delete_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycontrol',
            name='dateEnd',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='activitycontrol',
            name='dateStart',
            field=models.TimeField(),
        ),
    ]
