# Generated by Django 5.0.7 on 2024-07-24 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitycontrol', '0004_alter_activitycontrol_dateend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitycontrol',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 24)),
            preserve_default=False,
        ),
    ]
