# Generated by Django 5.1.1 on 2024-10-29 12:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('partnerType', models.CharField(max_length=2)),
                ('nationalId', models.FloatField()),
                ('address', models.CharField(max_length=255)),
            ],
        ),
    ]
